logging:
  level:
    cn.alphahub.eport.signature: debug
    org.apache.http: error
    org.springframework.core: warn
    org.springframework.beans: warn
    org.springframework.context: warn
    org.springframework.web: warn
    org.springframework.web.servlet: info
    org.springframework.cloud.openfeign: debug
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.context.support.PropertySourcesPlaceholderConfigurer: info
    org.springframework.security.core.userdetails: debug
    org.springframework.jdbc.datasource.DataSourceTransactionManager: debug
    jdbc.sqltiming: debug
    com.alibaba.cloud.nacos.client: error
    com.alibaba.nacos: error

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 101.34.184.17:8848

  jackson:
    default-property-inclusion: non_null

  #邮件通知配置，默认：不启用
  mail:
    enable: false
    #主收件人邮箱
    to: "abc@qq.com"
    #抄送箱邮（非必填）,抄送多个收件人箱邮用","隔开
    cc: 'abc@outlook.com,cbd@qq.com'
    #以下发送邮件的客服端参数，使用哪个邮箱发出通知消息
    host: "smtp.189.cn" #邮件服务商主机
    port: 465 #端口号
    username: "xxx@189.cn"
    password: "your_password"
    protocol: "smtp" #协议
    properties:
      mail:
        smtp:
          ssl:
            enable: true
        debug: false #是否开始debug模式，终端会打印日志

#电子口岸u-key的配置参数
eport:
  signature:
    ukey:
      # u-key的.cer证书在classpath的相对路径
      cert-path: cert/01691fe9.cer
      ws-url: ws://127.0.0.1:61232
      password: 88888888
      health:
        endpoint:
          # Windows上重启的ukey可执行文件全限定文件名称
          client-name: C:\中国电子口岸客户端控件\SetAccessControl.exe
