logging:
  level:
    cn.alphahub.eport.signature: debug
    org.apache.http: error
    org.springframework.core: warn
    org.springframework.beans: warn
    org.springframework.context: warn
    org.springframework.web: warn
    org.springframework.web.servlet: info
    org.springframework.cloud.openfeign: debug
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.context.support.PropertySourcesPlaceholderConfigurer: info
    org.springframework.security.core.userdetails: debug
    org.springframework.jdbc.datasource.DataSourceTransactionManager: debug
    jdbc.sqltiming: debug
    com.alibaba.cloud.nacos.client: error
    com.alibaba.nacos: error
  file:
    path: ./logs/
    name: ${logging.file.path}/${spring.application.name}.log
  charset:
    file: UTF-8
  logback:
    rollingpolicy:
      max-file-size: 5MB
      clean-history-on-start: true

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 101.34.184.17:8848
  jackson:
    default-property-inclusion: non_null

  #邮件通知配置，默认：不启用
  mail:
    enable: false
    #主收件人邮箱
    to: "abc@qq.com"
    #抄送箱邮（非必填）,抄送多个收件人箱邮用","隔开
    cc: 'abc@outlook.com,cbd@qq.com'
    #以下发送邮件的客服端参数，使用哪个邮箱发出通知消息
    host: "smtp.189.cn" #邮件服务商主机
    port: 465 #端口号
    username: "xxx@189.cn"
    password: "your_password"
    protocol: "smtp" #协议
    properties:
      mail:
        smtp:
          ssl:
            enable: true
        debug: false #是否开始debug模式，终端会打印日志

#中国电子口岸u-key的配置参数
eport:
  signature:
    algorithm: sm2_sm3
    ukey:
      ws-url: ws://127.0.0.1:61232
      password: 88888888
      health:
        endpoint:
          # Windows上重启的ukey可执行文件全限定文件名称
          client-name: C:\中国电子口岸客户端控件\SetAccessControl.exe
    # 客户端请求鉴权token, 生产环境不建议使用默认token
    auth:
      enable: true
      token: DefaultAuthToken
    # 报文传输的企业元数据配置（数据上报）
    report:
      # CEBMessage XML加签配置
      ceb-message:
        cop-code: '传输企业代码'
        cop-name: '海南省荣誉进出口贸易有限公司'
        dxp-id: '向中国电子口岸数据中心申请数据交换平台的用户编号'
        # 数据上报服务器地址，格式: http://ip:port, 缺省将采用默认server
        server:
      # 海关 179 数据抓取配置
      customs179:
        ebp-code: '电商平台代码'
        # server可为空，配置文件中指定时，将被优先使用
        server: https://海关服务器域名不方便公开/ceb2grab/grab/realTimeDataUpload
